name: fikzuas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_swiper_null_safety: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  particles_flutter: ^0.1.4
  flutter_tilt: ^2.0.0
  shared_preferences: ^2.3.0
  glassmorphism: ^3.0.0
  simple_animations: ^5.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/